[build]
builder = "nixpacks"
buildCommand = "npm install && npm run migrate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[env]
NODE_VERSION = "16"
NPM_CONFIG_PRODUCTION = "true"

[experimental]
autoRollback = true
