services:
  - type: web
    name: sereko-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: $PORT
    autoDeploy: true
    branch: master
    healthCheckPath: /health
